### ISSUE TITLE
initialization scrolls to the top

### ISSUE THREAD

**Issue by akhmerov** [executablebooks/sphinx-thebelab#3]
Observed on rtd. Clicking the thebelab button in the middle of the document moves the scroll to the top. I don't think that's a desirable behavior.

**Comment by choldgraf** [comment]
Huh - what browser are you using? This doesn't happen for me (on Chrome)

**Comment by akhmerov** [comment]
Also Chrome, but it's gone now ¯\\\_(ツ)\_/¯
