### ISSUE TITLE
Bad PyPI Homepage Link

### ISSUE THREAD

**Issue by rmorshea** [executablebooks/sphinx-thebelab#5]
PyPI links here: https://github.com/ExecutableBookProject/sphinx-thebelab

Instead of here: https://github.com/executablebooks/sphinx-thebelab

**Comment by choldgraf** [comment]
hmmm that is weird - do you have any idea how to change that link?

**Comment by choldgraf** [comment]
lol probably here https://github.com/executablebooks/sphinx-thebelab/blob/master/setup.py#L23 🤦

**Comment by choldgraf** [comment]
fixed on master!
