### ISSUE TITLE
Missing info about limitations

### ISSUE THREAD

**Issue by deeplook** [executablebooks/sphinx-thebelab#6]
Thanks for this really cool extension! I wonder where its limits are and miss some info in the docs. Like I was surprised to be able to see Matplotlib plots working in these Sphinx "cells", I was able to "pip install ipyleaflet", but I got an "Error displaying widget" when trying to show a simple map. What is expected to work and what isn't?

<img width="672" alt="Screenshot 2020-07-02 at 10 35 16" src="https://user-images.githubusercontent.com/1001778/86336225-df1ed700-bc4f-11ea-85c1-27f380fbf801.png">

**Comment by choldgraf** [comment]
I think I'm addressing some of this in #7 - lemme know what you think!

**Comment by deeplook** [comment]
That's better. it does make me wonder though, if any HTML output that requires some additional Javascript library will simply not work?

**Comment by choldgraf** [comment]
most likely, unless the page on which you're running Thebelab also has that library loaded (the same is true for any Jupyter environment, it's just that those environments also have the javascript libraries loaded)
